name: google_maps_webapi
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.24
homepage: https://github.com/rvndsngwn/google_maps_webapi

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  http: ^1.2.2
  meta: ^1.15.0
  json_annotation: ^4.9.0

dev_dependencies:
  test: ^1.25.14
  lints: ^5.1.1
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  coverage: ^1.11.1
