name: google_maps_webapi
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.21
homepage: https://github.com/rvndsngwn/google_maps_webapi

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.6
  meta: ^1.3.0
  json_annotation: ^4.0.0

dev_dependencies:
  test: ^1.16.0
  lints: ^2.1.0
  build_runner: ^2.4.1
  json_serializable: ^6.6.1
  coverage: ^1.0.0
